language: python
python:
  - "2.7"
# command to install dependencies
install: 
    - pip install -r requirements.txt
    - python -c "import nltk ; nltk.download(['gutenberg', ])"
# command to run tests
script: 
    - python linked_list_test.py
    - python stack_test.py
    - python queue_test.py
    - python hash_table_test.py
    - python bst_test.py
    - python insertion_sort_test.py
    - python merge_sort_test.py
