language: python
python:
  - "2.7"
# command to install dependencies
install: 
    - pip install -r requirements.txt
    - sudo mv nltk_data /usr/share/nltk_data
# command to run tests
script: 
    - python linked_list_test.py
    - python stack_test.py
    - python queue_test.py
    - python hash_table_test.py
